Repository Automattic/woocommerce-services, pull requests merged in 2018-05, with the labels that each got.

#1380 Surface missing weight error directly in admin notice
  classes/class-wc-connect-api-client.php
  classes/class-wc-connect-error-notice.php
  classes/class-wc-connect-logger.php
Labels: [Status] Ready to Merge

#1391 Adapt order page link to label settings' new section slug
  client/apps/settings/components/settings-form/settings-item.js
  client/apps/shipping-label/view-wrapper.js
Labels: [Status] Ready to Merge

#1396 Update Calypso Dependency
  assets/stylesheets/style.scss
  client/lib/pdf-label-utils/index.js
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1406 Admin breaking when product with missing weight is deleted
  classes/class-wc-connect-error-notice.php
Labels: [Pri] CRITICAL, [Status] Needs Review, [Type] Bug

#1370 Error message on manual service data refresh failure
  classes/class-wc-connect-help-view.php
Labels: [Status] Ready to Merge

#1425 Update Calypso dependency
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1426 Fix 'missing weight' admin notice's product link URL for variations
  classes/class-wc-connect-error-notice.php
Labels: [Status] Ready to Merge
