Repository Automattic/woocommerce-services, pull requests merged in 2018-03, with the labels that each got.

#1322 Updated the versions matrix to test our code in CI
  .travis.yml
  tests/php/test_class-wc-connect-api-client.php
Labels: [Status] Ready to Merge

#1332 Fix crash when there's an error requesting taxes from the WCS proxy.
  classes/class-wc-connect-taxjar-integration.php
Labels: Taxes, [Status] Ready to Merge

#1311 Forward specific address normalization errors, as success response
  classes/class-wc-rest-connect-address-normalization-controller.php
Labels: [Status] Ready to Merge

#1342 Fix various styling inconsistencies
  assets/stylesheets/style.scss
  client/apps/shipping-label/style.scss
  client/components/error-notice/index.js
  client/components/error-notice/style.scss
Labels: [Status] Ready to Merge

#1329 Add customer selected shipping method to rates step.
  client/api/request.js
  client/apps/shipping-label/index.js
  client/apps/shipping-label/view-wrapper.js
  client/calypso-stubs/config.js
  client/calypso-stubs/extensions/woocommerce/state/sites/http-request.js
  client/lib/local-api-middleware.js
  client/main.js
  npm-shrinkwrap.json
  package.json
  tasks/i18njson.js
  tasks/release.js
Labels: Shipping Labels, UI / UX, [Status] Ready to Merge, [Type] Enhancement

#1354 Send a no-cache header for WCS REST API responses.
  classes/class-wc-rest-connect-base-controller.php
Labels: REPORTED BY USER, [Pri] High, [Status] Ready to Merge, [Type] Bug

#1338 Include warning message in response upon failure to retrieve payment methods
  assets/stylesheets/style.scss
  classes/class-wc-connect-payment-methods-store.php
  classes/class-wc-rest-connect-account-settings-controller.php
Labels: [Status] Ready to Merge
