Repository Automattic/woocommerce-services, pull requests merged in 2018-02, with the labels that each got.

#1308 Fix waay too many automated tax requests
  classes/class-wc-connect-taxjar-integration.php
Labels: Taxes, [Status] Ready to Merge, [Type] Bug

#1290 Stripe Connect: Clear keys on stripe deauthorization
  classes/class-wc-connect-stripe.php
Labels: [Status] Ready to Merge

#1304 Add feature separated logging
  classes/class-wc-connect-help-view.php
  classes/class-wc-connect-logger.php
  tests/php/test_woocommerce-connect-client.php
  woocommerce-services.php
Labels: [Status] Ready to Merge

#1303 Output shipping debug messages on the Cart and Checkout pages.
  classes/class-wc-connect-help-view.php
  classes/class-wc-connect-logger.php
  classes/class-wc-connect-options.php
  classes/class-wc-connect-payment-methods-store.php
  classes/class-wc-connect-service-schemas-store.php
  classes/class-wc-connect-service-settings-store.php
  classes/class-wc-connect-shipping-method.php
  classes/class-wc-connect-taxjar-integration.php
  classes/class-wc-connect-tracks.php
  classes/class-wc-rest-connect-account-settings-controller.php
  classes/class-wc-rest-connect-address-normalization-controller.php
  classes/class-wc-rest-connect-self-help-controller.php
  classes/class-wc-rest-connect-services-controller.php
  classes/class-wc-rest-connect-shipping-label-controller.php
  classes/class-wc-rest-connect-shipping-label-preview-controller.php
  classes/class-wc-rest-connect-shipping-label-print-controller.php
  classes/class-wc-rest-connect-shipping-label-refund-controller.php
  classes/class-wc-rest-connect-shipping-label-status-controller.php
  classes/class-wc-rest-connect-shipping-rates-controller.php
  classes/class-wc-rest-connect-stripe-account-controller.php
  classes/class-wc-rest-connect-stripe-deauthorize-controller.php
  classes/class-wc-rest-connect-stripe-oauth-connect-controller.php
  classes/class-wc-rest-connect-stripe-oauth-init-controller.php
  tests/php/test_class-wc-connect-shipping-method.php
  tests/php/test_woocommerce-connect-client.php
  tests/php/test_woocommerce-connect-tracks.php
  woocommerce-services.php
Labels: Self Help, Shipping Rates, Usability, [Status] Ready to Merge, [Type] Enhancement
