Repository Automattic/woocommerce-services, pull requests merged in 2018-11, with the labels that each got.

#1538 Don't show admin notice for "unactionable" events
  classes/class-wc-connect-error-notice.php
Labels: Self Help, UI / UX, [Status] Ready to Merge

#1536 Show admin notice for missing product dimension errors
  classes/class-wc-connect-api-client.php
  classes/class-wc-connect-error-notice.php
  i18n/languages/woocommerce-services-es_ES.mo
  i18n/languages/woocommerce-services-es_ES.po
  i18n/languages/woocommerce-services-es_MX.mo
  i18n/languages/woocommerce-services-es_MX.po
  i18n/languages/woocommerce-services-fr_CA.mo
  i18n/languages/woocommerce-services-fr_CA.po
  i18n/languages/woocommerce-services-fr_FR.mo
  i18n/languages/woocommerce-services-fr_FR.po
  i18n/languages/woocommerce-services.pot
  i18n/strings.php
Labels: Self Help, Shipping Rates, UI / UX, [Status] Ready to Merge, [Type] Enhancement

#1540 Removing the background of borderless buttons in hover state
  assets/stylesheets/style.scss
Labels: [Status] Needs Review

#1545 Update calypso dependency to catch the update to `npm-run-all`.
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review
