Repository Automattic/woocommerce-services, pull requests merged in 2018-10, with the labels that each got.

#1509 Clean-up dev tools and logic that has never quite worked
  client/apps/plugin-status/index.js
  client/apps/print-test-label/index.js
  client/main.js
  npm-shrinkwrap.json
  package.json
Labels: Code Cleanup, [Status] Ready to Merge

#1510 Remove all our testing infrastructure, since all the JS tests are in wp-calypso
  karma.conf.js
  npm-shrinkwrap.json
  package.json
  webpack.config.js
Labels: Code Cleanup, [Status] Ready to Merge

#1511 Update NodeJS version to 10.11.0, to keep up with Calypso
  .nvmrc
  README.md
Labels: [Status] Ready to Merge

#1518 Remove “live rates” from NUX banner feature list.
  classes/class-wc-connect-nux.php
Labels: [Status] Ready to Merge

#1515 Remove “live shipping rates” as a feature in plugin README.
  CONTRIBUTING.md
  DEVELOPER.md
  README.md
  i18n/languages/woocommerce-services-es_ES.mo
  i18n/languages/woocommerce-services-es_ES.po
  i18n/languages/woocommerce-services-es_MX.mo
  i18n/languages/woocommerce-services-es_MX.po
  i18n/languages/woocommerce-services-fr_CA.mo
  i18n/languages/woocommerce-services-fr_CA.po
  i18n/languages/woocommerce-services-fr_FR.mo
  i18n/languages/woocommerce-services-fr_FR.po
  i18n/languages/woocommerce-services.pot
  i18n/strings.php
  readme.txt
  woocommerce-services.php
  wordpress_org_assets/screenshot-10.png
  wordpress_org_assets/screenshot-2.png
  wordpress_org_assets/screenshot-3.png
  wordpress_org_assets/screenshot-4.png
  wordpress_org_assets/screenshot-5.png
  wordpress_org_assets/screenshot-6.png
  wordpress_org_assets/screenshot-7.png
  wordpress_org_assets/screenshot-8.png
  wordpress_org_assets/screenshot-9.png
Labels: [Status] Ready to Merge

#1519 Release 1.17.0
  i18n/json/woocommerce-services-es_ES.json
  i18n/json/woocommerce-services-es_MX.json
  i18n/json/woocommerce-services-fr_CA.json
  i18n/json/woocommerce-services-fr_FR.json
  i18n/languages/woocommerce-services-es_ES.mo
  i18n/languages/woocommerce-services-es_ES.po
  i18n/languages/woocommerce-services-es_MX.mo
  i18n/languages/woocommerce-services-es_MX.po
  i18n/languages/woocommerce-services-fr_CA.mo
  i18n/languages/woocommerce-services-fr_CA.po
  i18n/languages/woocommerce-services-fr_FR.mo
  i18n/languages/woocommerce-services-fr_FR.po
  i18n/languages/woocommerce-services.pot
  package.json
  readme.txt
  woocommerce-services.php
  wordpress_org_assets/banner-1544x500.png
  wordpress_org_assets/banner-772x250.png
Labels: [Status] Ready to Merge

#1521 Remove “add method to zone” NUX pointer.
  classes/class-wc-connect-nux.php
Labels: Code Cleanup, Live Rates, Shipping Rates, [Status] Needs Review, [Type] Bug
