Repository Automattic/woocommerce-services, pull requests merged in 2018-06, with the labels that each got.

#1428 Respond with real HTTP errors when the shipping settings can't be validated
  classes/class-wc-connect-service-settings-store.php
  classes/class-wc-rest-connect-services-controller.php
Labels: [Status] Ready to Merge

#1398 Updated TaxJar integration
  classes/class-wc-connect-taxjar-integration.php
Labels: Taxes, [Status] Ready to Merge

#1430 Don't show "add method to zone" pointer if shipping was opted into
  classes/class-wc-connect-nux.php
  woocommerce-services.php
Labels: On-boarding, Shipping Rates, UI / UX, [Status] Needs Review

#1439 Save defaults when adding new WCS shipping method
  woocommerce-services.php
Labels: Settings

#1442 Updated nodeJS version to 10.4.0 and npm version to 6.1.0
  .nvmrc
  README.md
  assets/stylesheets/_components.scss
  assets/stylesheets/style.scss
  npm-shrinkwrap.json
  package.json
Labels: Build, [Status] Ready to Merge

#1444 Update Calypso to 9d78dbb - bypass address verification.
  assets/stylesheets/_components.scss
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1434 Refresh service schemas when specific WooCommerce settings are updated
  woocommerce-services.php
Labels: [Status] Ready to Merge

#1450 Update TaxJar to the latest version
  classes/class-wc-connect-taxjar-integration.php
Labels: Taxes, [Status] Ready to Merge

#1452 Release 1.15.0
  npm-shrinkwrap.json
  package.json
  readme.txt
  woocommerce-services.php
  wordpress_org_assets/banner-1544x500.png
  wordpress_org_assets/banner-772x250.png
  wordpress_org_assets/screenshot-1.png
  wordpress_org_assets/screenshot-10.png
  wordpress_org_assets/screenshot-6.png
Labels: [Status] Ready to Merge
