Repository Automattic/woocommerce-services, pull requests merged in 2018-12, with the labels that each got.

#1547 Replace alarming Stripe settings notice with helpful text
  classes/class-wc-connect-stripe.php
  client/apps/stripe-connect-account/view-wrapper.js
Labels: [Pri] High, [Status] Ready to Merge

#1546 Changing the shipping_phone field to avoid conflicts
  woocommerce-services.php
Labels: [Status] Ready to Merge

#1542 Display packing log in frontend debug and on order details
  assets/stylesheets/style.scss
  classes/class-wc-connect-shipping-method.php
  i18n/languages/woocommerce-services-es_ES.mo
  i18n/languages/woocommerce-services-es_ES.po
  i18n/languages/woocommerce-services-es_MX.mo
  i18n/languages/woocommerce-services-es_MX.po
  i18n/languages/woocommerce-services-fr_CA.mo
  i18n/languages/woocommerce-services-fr_CA.po
  i18n/languages/woocommerce-services-fr_FR.mo
  i18n/languages/woocommerce-services-fr_FR.po
  i18n/languages/woocommerce-services.pot
  woocommerce-services.php
Labels: [Status] Ready to Merge

#1554 Fix missing button colors with latest Calypso
  assets/stylesheets/style.scss
Labels: [Status] Ready to Merge

#1555 Updating the Calypso refspec to include all merged PRs for 1.18.0
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1549 Add specificity to root selector to avoid conflicts in Calypsoified wp-admin.
  assets/stylesheets/style.scss
  webpack.config.js
Labels: [Status] Needs Review

#1513 Add Stripe OAuth connect action into settings
  classes/class-wc-connect-stripe.php
  classes/class-wc-rest-connect-stripe-oauth-init-controller.php
  client/apps/stripe-connect-account/style.scss
  client/apps/stripe-connect-account/view-wrapper.js
Labels: [Status] Needs Design, [Status] Ready to Merge
