Repository Automattic/woocommerce-services, pull requests merged in 2019-05, with the labels that each got.

#1597 Update shipping label button to primary
  client/apps/shipping-label/view-wrapper.js
Labels: [Status] Needs Design, [Status] Ready to Merge

#1615 Tweak stripe key error message slightly
  classes/class-wc-connect-stripe.php
Labels: [Status] Ready to Merge

#1612 Release v1.20
  npm-shrinkwrap.json
  package.json
  readme.txt
  woocommerce-services.php
Labels: [Status] Needs Review
