Repository Automattic/woocommerce-services, pull requests merged in 2021-08, with the labels that each got.

#2449 Update npm-shrinkwrap.json
  docker/mu-dev.php
  docker/mu-wccon-staging.php
  npm-shrinkwrap.json
  package.json
Labels: [Pri] Low, dependencies

#2466 Fix fatal error when viewing a draft order
  changelog.txt
  classes/class-wc-connect-order-presenter.php
  tests/php/test-class-wc-connect-order-presenter.php
Labels: [Status] Ready to Merge

#2468 Fix PHP Notice: Undefined property: stdClass::$commercial_invoice_url
  changelog.txt
  classes/class-wc-rest-connect-shipping-label-controller.php
Labels: [Status] Needs Review

#2465 feat: add automatic tax health item
  changelog.txt
  classes/class-wc-connect-help-view.php
  classes/class-wc-connect-taxjar-integration.php
  client/apps/plugin-status/health.js
  client/apps/plugin-status/test/health.test.js
  woocommerce-services.php
Labels: [Status] Ready to Merge
