Repository Automattic/woocommerce-services, pull requests merged in 2021-07, with the labels that each got.

#2450 Update WP version used by E2E tests to 5.7.2
  .github/workflows/e2e_tests.yml
Labels: [Pri] High, [Type] E2E

#2444 fix: typo in debug tools message
  classes/class-wc-connect-debug-tools.php
  npm-shrinkwrap.json
Labels: [Status] Has PR, [Status] Needs Review

#2447 feat: add dev docker image
  .github/workflows/e2e_tests.yml
  .gitignore
  README.md
  bin/docker-setup.sh
  bin/jurassic-tube-setup.sh
  default.env
  docker-compose.yml
  docker/mu-dev.php
  docker/mu-wccon-staging.php
  docker/php.ini
  docker/wordpress_xdebug/Dockerfile
  package.json
Labels: [Status] Needs Review

#2448 Replace Calypso FormCheckbox with CheckboxControl.
  client/extensions/woocommerce/woocommerce-services/components/checkbox/style.scss
  client/extensions/woocommerce/woocommerce-services/views/label-settings/label-payment-method.js
  client/extensions/woocommerce/woocommerce-services/views/label-settings/label-settings.js
  client/extensions/woocommerce/woocommerce-services/views/label-settings/style.scss
  client/extensions/woocommerce/woocommerce-services/views/packages/predefined-packages.js
  client/extensions/woocommerce/woocommerce-services/views/packages/style.scss
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/add-item.js
Labels: [Status] Needs Review

#2445 deps: upgrade husky
  .husky/pre-commit
  .husky/pre-push
  npm-shrinkwrap.json
  package.json
Labels: [Status] Has PR, [Status] Needs Review

#2459 Do not fail on `npm run update-deps` if npm-shrinkwrap.json is missing
  package.json
Labels: [Pri] Low, [Type] Technical Debt

#2461 chore: update WP/WC tested versions
  .github/workflows/e2e_tests.yml
  changelog.txt
  readme.txt
  woocommerce-services.php
Labels: [Status] Needs Review
