Repository Automattic/woocommerce-services, pull requests merged in 2021-03, with the labels that each got.

#2344 Replace Calypso Fieldset with internal Fieldset
  client/components/forms/form-fieldset/index.js
  client/components/forms/form-fieldset/style.scss
Labels: [Status] Needs Review

#2341 Replace Calypso FormToggle with WP component
  client/components/toggle/index.js
  client/extensions/woocommerce/woocommerce-services/views/label-settings/index.js
  client/extensions/woocommerce/woocommerce-services/views/label-settings/style.scss
Labels: [Status] Needs Review

#2339 refactor: status page refresh with ajax call
  changelog.txt
  classes/class-wc-connect-help-view.php
  classes/class-wc-rest-connect-service-data-refresh-controller.php
  client/api/url.js
  client/apps/plugin-status/health.js
  client/apps/plugin-status/indicator.js
  client/apps/plugin-status/state/action-types.js
  client/apps/plugin-status/state/actions.js
  client/apps/plugin-status/state/reducer.js
  client/apps/plugin-status/test/health.test.js
  client/apps/plugin-status/view.js
  client/apps/plugin-status/woocommerce-services-indicator.js
  client/components/toggle/index.js
  package.json
  woocommerce-services.php
Labels: [Status] Needs Review

#2346 fix: jetpack deprecation of Jetpack_Data
  changelog.txt
  classes/class-wc-connect-api-client-live.php
  classes/class-wc-connect-api-client.php
  classes/class-wc-connect-jetpack.php
  classes/class-wc-connect-nux.php
  readme.txt
  woocommerce-services.php
Labels: [Status] Needs Review

#2351 Replace FormTextInput in TextField component
  assets/stylesheets/_colors.scss
  client/extensions/woocommerce/woocommerce-services/components/text-field/index.js
  client/extensions/woocommerce/woocommerce-services/components/text-field/style.scss
  client/extensions/woocommerce/woocommerce-services/style.scss
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/dynamic-settings-form.test.js
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/ups-settings-form.test.js
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/ups-settings-form.js
  client/extensions/woocommerce/woocommerce-services/views/label-settings/index.js
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/customs-step/style.scss
Labels: [Status] Ready to Merge

#2318 Add API support for creating packages with POST and updating packages with PUT
  changelog.txt
  classes/class-wc-connect-service-settings-store.php
  classes/class-wc-rest-connect-base-controller.php
  classes/class-wc-rest-connect-packages-controller.php
  client/api/request.js
  client/extensions/woocommerce/woocommerce-services/api/index.js
  client/extensions/woocommerce/woocommerce-services/state/packages/actions.js
  tests/php/classes/test-class-wc-rest-connect-packages-controller.php
  tests/php/test_class-wc-connect-service-settings-store.php
Labels: Shipping Labels

#2354 Replace FormTextInputWithAffixes with WooCommerce Component
  assets/stylesheets/_components.scss
  assets/stylesheets/style.scss
  client/components/forms/text-control-with-affixes/index.js
  client/components/forms/text-control-with-affixes/style.scss
  client/extensions/woocommerce/components/form-dimensions-input/index.jsx
  client/extensions/woocommerce/components/form-dimensions-input/style.scss
  client/extensions/woocommerce/woocommerce-services/components/number-field/index.js
  client/extensions/woocommerce/woocommerce-services/components/number-field/number-input.js
  client/extensions/woocommerce/woocommerce-services/components/weight-field/index.js
  client/extensions/woocommerce/woocommerce-services/views/packages/edit-package.js
  client/extensions/woocommerce/woocommerce-services/views/service-settings/shipping-services/entry.js
  client/extensions/woocommerce/woocommerce-services/views/service-settings/shipping-services/style.scss
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js
  npm-shrinkwrap.json
Labels: [Status] Needs Review

#2358 Replace Calypso FieldLabel with internal FieldLabel
  client/components/forms/form-label/index.js
  client/components/forms/form-label/style.scss
  client/components/toggle/index.js
Labels: [Status] Needs Review

#2375 feat: add live rates carriers list section
  changelog.txt
  classes/class-wc-connect-settings-pages.php
  client/apps/shipping-settings/index.js
  client/apps/shipping-settings/view-wrapper.js
  client/extensions/woocommerce/woocommerce-services/style.scss
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/index.js
  client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/carriers-list.js
  client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/index.js
  client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/style.scss
  client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/test/live-rates-carriers-list.test.js
  woocommerce-services.php
Labels: [Status] Needs Review

#2378 Fix condition to display DHL live rates notice.
  classes/class-wc-connect-note-dhl-live-rates-available.php
Labels: [Status] Needs Review

#2370 refactor: calypso form-select
  assets/stylesheets/_components.scss
  client/apps/print-test-label/view.js
  client/components/forms/form-select/index.js
  client/components/forms/form-select/styles.scss
  client/extensions/woocommerce/woocommerce-services/components/dropdown/index.js
  client/extensions/woocommerce/woocommerce-services/views/label-settings/label-settings.js
  client/extensions/woocommerce/woocommerce-services/views/packages/edit-package.js
  client/extensions/woocommerce/woocommerce-services/views/service-settings/shipping-services/entry.js
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-select.js
  tests/client/jest.config.js
  webpack.config.js
Labels: [Status] Needs Review

#2369 fix: broken status page
  client/components/forms/form-label/index.js
Labels: [Status] Needs Review

#2382 Fix PHP notice on carrier registration page
  classes/class-wc-connect-settings-pages.php
Labels: [Type] Bug

#2385 Unset translate() transform on radio buttons in label purchase modal
  changelog.txt
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss
Labels: [Type] Bug

#2384 chore: update carrier discount amounts
  client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/carriers-list.js
Labels: [Status] Ready to Merge

#2334 Add an endpoint for shipping label creation eligibility for Woo mobile
  changelog.txt
  classes/class-wc-connect-shipping-label.php
  classes/class-wc-rest-connect-shipping-label-controller.php
  tests/php/classes/test-class-wc-rest-connect-shipping-label-controller.php
  tests/php/test-class-wc-connect-shipping-label.php
  woocommerce-services.php
Labels: Shipping Labels

#2368 fix: status page in new WC navigation
  changelog.txt
  woocommerce-services.php
Labels: [Status] Ready to Merge

#2392 feat: spinner icon on service data fetch
  changelog.txt
  client/apps/plugin-status/indicator.js
  client/apps/plugin-status/state/actions.js
  client/apps/plugin-status/style.scss
  client/apps/plugin-status/woocommerce-services-indicator.js
Labels: [Status] Needs Review

#2224 Integrate `@woocommerce/e2e-environment` package for the e2e tests
  .eslintignore
  .eslintrc.js
  .github/workflows/e2e_tests.yml
  .github/workflows/js_tests.yml
  changelog.txt
  classes/class-wc-connect-settings-pages.php
  classes/class-wc-rest-connect-base-controller.php
  npm-shrinkwrap.json
  package.json
  tests/bin/get-base-url.js
  tests/bin/wait-for-e2e-build.sh
  tests/bin/wc_rest_api_credentials.php
  tests/e2e-tests/config/travis/wc-services-testing-helper.php
  tests/e2e-tests/jest-puppeteer.config.js
  tests/e2e/README.md
  tests/e2e/config/default.json
  tests/e2e/config/jest-puppeteer.config.js
  tests/e2e/config/jest.config.js
  tests/e2e/config/jest.setup.js
  tests/e2e/config/jest.test.failure.js
  tests/e2e/config/travis/travis_default-site.conf
  tests/e2e/config/travis/travis_fastcgi.conf
  tests/e2e/config/travis/travis_nginx.conf
  tests/e2e/config/travis/travis_php-fpm.conf
  tests/e2e/config/travis/wc-services-testing-helper.php
  tests/e2e/docker/initialize.sh
  tests/e2e/fixtures/account_settings.js
  tests/e2e/fixtures/create-shipping-label.json
  tests/e2e/fixtures/index.js
  tests/e2e/fixtures/orders.json
  tests/e2e/fixtures/products.json
  tests/e2e/fixtures/test_data.json
  tests/e2e/lib/reporter/slack-reporter.js
  tests/e2e/mocks/index.js
  tests/e2e/specs/admin/1-activate-extension.test.js
  tests/e2e/specs/admin/2-shipping-settings.test.js
  tests/e2e/specs/admin/3-create-shipping-label.test.js
  tests/e2e/specs/admin/4-refund-label.test.js
  tests/e2e/utils/components.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/index.js
  tests/php/classes/test-class-wc-rest-connect-shipping-label-controller.php
  webpack.config.js
Labels: [Status] In Progress, [Type] E2E
