Repository Automattic/woocommerce-services, pull requests merged in 2021-02, with the labels that each got.

#2303 Fix radio button dot alignment in "Create shipping label"
  changelog.txt
  client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss
Labels: [Type] Bug

#2306 Disable E2E tests unless env(DONT_SKIP_E2E_TESTS) is present
  .travis.yml
Labels: [Type] E2E, [Type] Technical Debt

#2338 Make UPS Invoice field accept numbers and letters.
  changelog.txt
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/ups-settings-form.test.js
  client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/ups-settings-form.js
  npm-shrinkwrap.json
Labels: [Status] Needs Review
